In [3]:
#Libraries
import numpy as np

# **Creating numpy n-d Array**


In [4]:
arr1=np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [5]:
type(arr1)

numpy.ndarray

In [6]:
arr2=np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
arr3=np.zeros((2,3))  # 2 rows, 3 columns
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [8]:
arr4=np.ones((3,3))  # 3 rows, 3 columns
arr4

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [9]:
arr5=np.identity(3)  # 3x3 identity matrix
arr5

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [10]:
arr6=np.arange(10)   #Generates an array with values from 0 to 9
arr6

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
arr7=np.arange(5,16)   #Generates an array with range of 5 to 15
arr7

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [12]:
arr8=np.arange(0,17,2)  #Generates an array with values from 0 to 16 with step of 2
arr8

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16])

In [13]:
arr9=np.linspace(10,20,10)  #Generates an array with 10 values evenly spaced between 10 and 20
arr9                        #The difference between the two numbers will always be same

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [14]:
arr10=arr9.copy() #Creates a copy of arr9
arr10

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

# **Numpy Array Properties And Attributes**

1.Shape
2.nDim
3.Size
4.Itemsize
5.Dtype
6.astype()

In [15]:
arr1.shape #Returns the shape of the array (rows, columns)

(5,)

In [16]:
arr9=np.array([[ [1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr9   #3-d Array

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [17]:
arr9.shape  #Shape of the array

(2, 2, 3)

In [18]:
arr9.ndim

3

In [19]:
arr9.size

12

In [20]:
arr9.itemsize

8

In [21]:
arr8.dtype

dtype('int64')

In [22]:
#Type casting
arr8.astype(float)

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16.])

# **Numpy Array VS Python List**

In [23]:
list=range(100)
arr11=np.arange(100) 

In [24]:
import sys 

# Array are faster

In [25]:
print("Size of list:", sys.getsizeof(87)* len(list))

Size of list: 2800


In [26]:
arr11 = np.arange(100)
print(arr11.itemsize * arr11.size)

800


In [27]:
import time

# takes more time during execution

In [28]:
x = range(10000000)
y = range(10000000, 20000000)
start_time = time.time()
c = [(x_val, y_val) for x_val, y_val in zip(x, y)]

print(time.time() - start_time)

1.5979197025299072


In [29]:
a=np.arange(10000000)
b=np.arange(10000000,20000000)   
start_time = time.time()
c=a+b 

print(time.time()-start_time)

0.5081226825714111


# **Indexing Iteration and Slicing**

In [30]:
arr13=np.arange(24).reshape(6,4) #Reshaping the array to 6 rows and 4 columns
arr13


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [31]:
arr13.ndim #Number of dimensions

2

In [32]:
arr13[2] #Accessing the 2nd row

array([ 8,  9, 10, 11])

In [33]:
arr13[:3] #Accessing the first 3 rows

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [34]:
arr13[: ,3] #Accessing the 3rd column

array([ 3,  7, 11, 15, 19, 23])

In [35]:
arr13[2,:]  #Accessing the 2nd row and all columns

array([ 8,  9, 10, 11])

In [36]:
arr13[:,1:3]  #Accessing all rows and columns from 1st to 2nd (exclusive)

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14],
       [17, 18],
       [21, 22]])

In [37]:
arr13[2:4,1:3]  #Accessing rows from 2nd to 3rd (exclusive) and columns from 1st to 2nd (exclusive)

array([[ 9, 10],
       [13, 14]])

In [38]:
arr13[0][3] #Accessing the element at 0th row and 3rd column

np.int64(3)

In [39]:
arr13.reshape(2,12)  #Reshaping the array to 2 rows and 12 columns
arr13.reshape(3,8)  #Reshaping the array to 3 rows and 8 columns
arr13.reshape(4,6)  #Reshaping the array to 4 rows and 6 columns

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

# **Mathematics**

In [40]:
a = [1, 2, 3]
b = [2, 2, 2]
np.sum([a,b])

np.int64(12)

In [41]:
a = [1, 2, 3]
b = [2,2,2]
np.sum([a, b],axis=0)  # Subtracting two arrays element-wise

array([3, 4, 5])

In [42]:
a = [1, 2, 3]
b = [2,2,2]
np.sum([a, b],axis=1)

array([6, 6])

In [43]:
print(a,b)
np.subtract(a, 2)  #Subtracting 2 from each element of the array

[1, 2, 3] [2, 2, 2]


array([-1,  0,  1])

In [44]:
print(a,b)
np.subtract(a, b)   

[1, 2, 3] [2, 2, 2]


array([-1,  0,  1])

In [45]:
print(a,b)
np.subtract([1, 2, 3], [4, 5, 6])  #Subtracting two arrays element-wise

[1, 2, 3] [2, 2, 2]


array([-3, -3, -3])

In [46]:
print(a,b)
np.multiply(a, 2)  #Multiplying each element of the array by 2

[1, 2, 3] [2, 2, 2]


array([2, 4, 6])

In [47]:
print(a,b)
np.multiply(a,b) #Multiplying two arrays element-wise

[1, 2, 3] [2, 2, 2]


array([2, 4, 6])

In [48]:
print(a,b)
np.divide(a, b) #Dividing two arrays element-wise

[1, 2, 3] [2, 2, 2]


array([0.5, 1. , 1.5])

In [49]:
np.exp(a) #Calculating the exponential of each element in the array

array([ 2.71828183,  7.3890561 , 20.08553692])

In [50]:
np.sqrt(a) #Calculating the square root of each element in the array

array([1.        , 1.41421356, 1.73205081])

In [51]:
np.sqrt(36) #Calculating the square root of a single number

np.float64(6.0)

In [52]:
np.sin(a) #Calculating the sine of each element in the array

array([0.84147098, 0.90929743, 0.14112001])

In [53]:
np.sin(90) #Calculating the sine of 90 degrees

np.float64(0.8939966636005579)

In [54]:
np.cos(90)  #Calculating the cosine of 90 degrees

np.float64(-0.4480736161291701)

In [55]:
np.log(a) #Calculating the natural logarithm of each element in the array

array([0.        , 0.69314718, 1.09861229])

In [56]:
np.log(10) #Calculating the natural logarithm of a single number

np.float64(2.302585092994046)

# **Array Comparison**

In [57]:
print(a,b)
np.equal(a, b)  #Checking if two arrays are equal element-wise

[1, 2, 3] [2, 2, 2]


array([False,  True, False])

In [58]:
print(a,b)
np.array_equal(a, b)  #Checking if two arrays are equal element-wise

[1, 2, 3] [2, 2, 2]


False

# **Aggregate Functions**

# **BroadCasting**

# Rules OF BroadCasting
1.Both arrays have same dimensions
# OR
2.Any one array has a dimension 1

In [59]:
a=np.array([[1, 2, 3, 4, 5],[6, 7, 8, 9, 10]])
b=np.array([6, 7, 8, 9, 10])    
a + b  #adding b to each row of a


array([[ 7,  9, 11, 13, 15],
       [12, 14, 16, 18, 20]])

In [60]:
a = np.array([1, 2, 3])
b = np.array([[1],[2],[3]])
a + b  # Broadcasting b to each row of a

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [61]:
a=np.array([[1, 2, 3, 4, 5],[6, 7, 8, 9, 10]])
b=np.array([6, 7, 8, 9, 10])    
a - b  #Subtracting b from each row of a


array([[-5, -5, -5, -5, -5],
       [ 0,  0,  0,  0,  0]])

In [ ]:
a = np.array([1, 2, 3])
b = np.array([[1],[2],[3]])
a - b

array([[ 0,  1,  2],
       [-1,  0,  1],
       [-2, -1,  0]])

# **Array Manipulation**

# Concatenate

In [63]:
a=np.array([1,2,3])
b=np.array([4,5,6])
np.concatenate((a, b), axis=0)  #Concatenating two arrays vertically

array([1, 2, 3, 4, 5, 6])

In [64]:
a=np.array([[1],[2]])
b=np.array([[3],[4]])
np.concatenate((a, b), axis=0)  #Concatenating two arrays vertically

array([[1],
       [2],
       [3],
       [4]])

In [65]:
np.concatenate((a, b), axis=1)  #Concatenating two arrays horizontally  

array([[1, 3],
       [2, 4]])

In [66]:
a=np.array([[1, 2, 3],[5,5,6]])
b=np.array([[4,5,6],[7,8,9]])
np.concatenate((a, b), axis=0)  #Concatenating two arrays vertically


array([[1, 2, 3],
       [5, 5, 6],
       [4, 5, 6],
       [7, 8, 9]])

In [67]:
np.concatenate((a, b), axis=1)  #Concatenating two arrays horizontally

array([[1, 2, 3, 4, 5, 6],
       [5, 5, 6, 7, 8, 9]])

In [68]:
aa=np.array([[1, 2, 3],
       [5, 5, 6],
       [4, 5, 6],
       [7, 8, 9]])
aa.shape

(4, 3)

In [69]:
bb=np.array([[1, 2, 3, 4, 5, 6],
       [5, 5, 6, 7, 8, 9]])
bb.shape

(2, 6)

# Stack

In [70]:
a=np.array([1,2,3])
b=np.array([4,5,6])
np.stack((a,b),axis=0)

array([[1, 2, 3],
       [4, 5, 6]])

In [71]:
np.stack((a,b)).shape

(2, 3)

In [72]:
np.stack((a,b),axis=1)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [73]:
np.stack((a,b),axis=1).shape

(3, 2)

In [74]:
a=np.array([[1,2,3],[3,4,5]])
b=np.array([[4,5,6],[6,7,8]])
np.stack((a,b),axis=0)

array([[[1, 2, 3],
        [3, 4, 5]],

       [[4, 5, 6],
        [6, 7, 8]]])

In [75]:
np.stack((a,b),axis=0).shape

(2, 2, 3)

In [76]:
np.stack((a,b),axis=1)

array([[[1, 2, 3],
        [4, 5, 6]],

       [[3, 4, 5],
        [6, 7, 8]]])

In [77]:
np.stack((a,b),axis=0).shape

(2, 2, 3)

# Vstack () and Hstack ()

In [78]:
a = np.array([[1, 2, 3], [3, 4, 5]])
b = np.array([[4, 5, 6], [6, 7, 8]])
np.vstack((a, b))  #Vertical stacking of two arrays

array([[1, 2, 3],
       [3, 4, 5],
       [4, 5, 6],
       [6, 7, 8]])

In [79]:
np.vstack((a, b)).shape 

(4, 3)

In [80]:
np.hstack((a, b)) #Horizontal stacking of two arrays
# Vstack () and Hstack ()

array([[1, 2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7, 8]])

In [81]:
np.hstack((a, b)).shape 

(2, 6)

In [82]:
np.column_stack((a,b))

array([[1, 2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7, 8]])

In [83]:
np.row_stack((a,b))  #Row stacking of two arrays

C:\Users\hp\AppData\Local\Temp\ipykernel_3068\1134470044.py:1: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  np.row_stack((a,b))  #Row stacking of two arrays


array([[1, 2, 3],
       [3, 4, 5],
       [4, 5, 6],
       [6, 7, 8]])

# **Array Splitting**

In [84]:
a=np.array([1,2,3,4])
np.split(a,2) #Splitting the array into 2 equal parts

[array([1, 2]), array([3, 4])]

In [107]:
np.split(a,2,axis=0) #Splitting the array into 2 equal parts along axis 0

[array([[1, 2, 3]]), array([[4, 5, 6]])]

In [ ]:
a=np.array([[1,2,3],[4,5,6]])
np.split(a,2,axis=0) #Splitting the array into 2 equal parts along axis 0


[array([[1, 2, 3]]), array([[4, 5, 6]])]

In [ ]:
np.split(a,3,axis=1) #Splitting the array into 3 equal parts along axis 1


# Row wise splitting

In [ ]:
# The indices_or_sections argument should be a list of indices, not a slice.
# For example, to split at row index 1 and 2 (i.e., get three splits: a[:1], a[1:2], a[2:]), use [1, 2]

np.split(a, [1, 2], axis=0)



[array([[1, 2, 3]]), array([[4, 5, 6]]), array([], shape=(0, 3), dtype=int64)]

In [124]:
a[:1,:]

array([[1, 2, 3]])

In [125]:
a[1:2,:]

array([[4, 5, 6]])

In [126]:
a[2:,:]

array([], shape=(0, 3), dtype=int64)

# Column wise splitting

In [120]:
np.split(a, [1,3], axis=1)



[array([[1],
        [4]]),
 array([[2, 3],
        [5, 6]]),
 array([], shape=(2, 0), dtype=int64)]

In [127]:
a[:,:1]

array([[1],
       [4]])

In [128]:
a[:,1:3]

array([[2, 3],
       [5, 6]])

In [130]:
a[:,3:]

array([], shape=(2, 0), dtype=int64)