In [4]:
#Libraries
import numpy as np

# **Creating numpy n-d Array**


In [5]:
arr1=np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [6]:
type(arr1)

numpy.ndarray

In [7]:
arr2=np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
arr3=np.zeros((2,3))  # 2 rows, 3 columns
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [9]:
arr4=np.ones((3,3))  # 3 rows, 3 columns
arr4

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [10]:
arr5=np.identity(3)  # 3x3 identity matrix
arr5

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [11]:
arr6=np.arange(10)   #Generates an array with values from 0 to 9
arr6

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
arr7=np.arange(5,16)   #Generates an array with range of 5 to 15
arr7

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [13]:
arr8=np.arange(0,17,2)  #Generates an array with values from 0 to 16 with step of 2
arr8

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16])

In [14]:
arr9=np.linspace(10,20,10)  #Generates an array with 10 values evenly spaced between 10 and 20
arr9                        #The difference between the two numbers will always be same

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [15]:
arr10=arr9.copy() #Creates a copy of arr9
arr10

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

# **Numpy Array Properties And Attributes**

1.Shape
2.nDim
3.Size
4.Itemsize
5.Dtype
6.astype()

In [16]:
arr1.shape #Returns the shape of the array (rows, columns)

(5,)

In [17]:
arr9=np.array([[ [1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr9   #3-d Array

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [18]:
arr9.shape  #Shape of the array

(2, 2, 3)

In [19]:
arr9.ndim

3

In [20]:
arr9.size

12

In [21]:
arr9.itemsize

8

In [22]:
arr8.dtype

dtype('int64')

In [23]:
#Type casting
arr8.astype(float)

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16.])

# **Numpy Array VS Python List**

In [29]:
list=range(100)
arr11=np.arange(100) 

In [28]:
import sys 

# Array are faster

In [29]:
print("Size of list:", sys.getsizeof(87)* len(list))

Size of list: 2800


In [30]:
arr11 = np.arange(100)
print(arr11.itemsize * arr11.size)

800


In [32]:
import time

# takes more time during execution

In [39]:
x = range(10000000)
y = range(10000000, 20000000)
start_time = time.time()
c = [(x_val, y_val) for x_val, y_val in zip(x, y)]

print(time.time() - start_time)

1.4866838455200195


In [38]:
a=np.arange(10000000)
b=np.arange(10000000,20000000)   
start_time = time.time()
c=a+b 

print(time.time()-start_time)

0.03235363960266113


# **Indexing Iteration and Slicing**

In [41]:
arr13=np.arange(24).reshape(6,4) #Reshaping the array to 6 rows and 4 columns
arr13


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
arr13.ndim #Number of dimensions

2

In [ ]:
arr13[2] #Accessing the 2nd row

array([ 8,  9, 10, 11])

In [48]:
arr13[:3] #Accessing the first 3 rows

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [47]:
arr13[: ,3] #Accessing the 3rd column

array([ 3,  7, 11, 15, 19, 23])

In [49]:
arr13[2,:]  #Accessing the 2nd row and all columns

array([ 8,  9, 10, 11])

In [50]:
arr13[:,1:3]  #Accessing all rows and columns from 1st to 2nd (exclusive)

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14],
       [17, 18],
       [21, 22]])

In [51]:
arr13[2:4,1:3]  #Accessing rows from 2nd to 3rd (exclusive) and columns from 1st to 2nd (exclusive)

array([[ 9, 10],
       [13, 14]])

In [ ]:
arr13[0][3] #Accessing the element at 0th row and 3rd column

np.int64(3)

In [ ]:
arr13.reshape(2,12)  #Reshaping the array to 2 rows and 12 columns
arr13.reshape(3,8)  #Reshaping the array to 3 rows and 8 columns
arr13.reshape(4,6)  #Reshaping the array to 4 rows and 6 columns