In [56]:
#Libraries
import numpy as np

# **Creating numpy n-d Array**


In [57]:
arr1=np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [58]:
type(arr1)

numpy.ndarray

In [59]:
arr2=np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [60]:
arr3=np.zeros((2,3))  # 2 rows, 3 columns
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [61]:
arr4=np.ones((3,3))  # 3 rows, 3 columns
arr4

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [62]:
arr5=np.identity(3)  # 3x3 identity matrix
arr5

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [63]:
arr6=np.arange(10)   #Generates an array with values from 0 to 9
arr6

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [64]:
arr7=np.arange(5,16)   #Generates an array with range of 5 to 15
arr7

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [65]:
arr8=np.arange(0,17,2)  #Generates an array with values from 0 to 16 with step of 2
arr8

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16])

In [66]:
arr9=np.linspace(10,20,10)  #Generates an array with 10 values evenly spaced between 10 and 20
arr9                        #The difference between the two numbers will always be same

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [67]:
arr10=arr9.copy() #Creates a copy of arr9
arr10

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

# **Numpy Array Properties And Attributes**

1.Shape
2.nDim
3.Size
4.Itemsize
5.Dtype
6.astype()

In [68]:
arr1.shape #Returns the shape of the array (rows, columns)

(5,)

In [69]:
arr9=np.array([[ [1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr9   #3-d Array

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [70]:
arr9.shape  #Shape of the array

(2, 2, 3)

In [71]:
arr9.ndim

3

In [72]:
arr9.size

12

In [73]:
arr9.itemsize

8

In [74]:
arr8.dtype

dtype('int64')

In [75]:
#Type casting
arr8.astype(float)

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16.])

# **Numpy Array VS Python List**

In [76]:
list=range(100)
arr11=np.arange(100) 

In [77]:
import sys 

# Array are faster

In [78]:
print("Size of list:", sys.getsizeof(87)* len(list))

Size of list: 2800


In [79]:
arr11 = np.arange(100)
print(arr11.itemsize * arr11.size)

800


In [ ]:
import time

# takes more time during execution

In [26]:
x = range(10000000)
y = range(10000000, 20000000)
start_time = time.time()
c = [(x_val, y_val) for x_val, y_val in zip(x, y)]

print(time.time() - start_time)

3.137221574783325


In [27]:
a=np.arange(10000000)
b=np.arange(10000000,20000000)   
start_time = time.time()
c=a+b 

print(time.time()-start_time)

0.73221755027771


# **Indexing Iteration and Slicing**

In [28]:
arr13=np.arange(24).reshape(6,4) #Reshaping the array to 6 rows and 4 columns
arr13


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [29]:
arr13.ndim #Number of dimensions

2

In [30]:
arr13[2] #Accessing the 2nd row

array([ 8,  9, 10, 11])

In [31]:
arr13[:3] #Accessing the first 3 rows

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [32]:
arr13[: ,3] #Accessing the 3rd column

array([ 3,  7, 11, 15, 19, 23])

In [33]:
arr13[2,:]  #Accessing the 2nd row and all columns

array([ 8,  9, 10, 11])

In [34]:
arr13[:,1:3]  #Accessing all rows and columns from 1st to 2nd (exclusive)

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14],
       [17, 18],
       [21, 22]])

In [35]:
arr13[2:4,1:3]  #Accessing rows from 2nd to 3rd (exclusive) and columns from 1st to 2nd (exclusive)

array([[ 9, 10],
       [13, 14]])

In [36]:
arr13[0][3] #Accessing the element at 0th row and 3rd column

np.int64(3)

In [37]:
arr13.reshape(2,12)  #Reshaping the array to 2 rows and 12 columns
arr13.reshape(3,8)  #Reshaping the array to 3 rows and 8 columns
arr13.reshape(4,6)  #Reshaping the array to 4 rows and 6 columns

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

# **Mathematics**

In [38]:
a = [1, 2, 3]
b = [2, 2, 2]
np.sum([a,b])

np.int64(12)

In [39]:
a = [1, 2, 3]
b = [2,2,2]
np.sum([a, b],axis=0)  # Subtracting two arrays element-wise

array([3, 4, 5])

In [40]:
a = [1, 2, 3]
b = [2,2,2]
np.sum([a, b],axis=1)

array([6, 6])

In [41]:
print(a,b)
np.subtract(a, 2)  #Subtracting 2 from each element of the array

[1, 2, 3] [2, 2, 2]


array([-1,  0,  1])

In [42]:
print(a,b)
np.subtract(a, b)   

[1, 2, 3] [2, 2, 2]


array([-1,  0,  1])

In [43]:
print(a,b)
np.subtract([1, 2, 3], [4, 5, 6])  #Subtracting two arrays element-wise

[1, 2, 3] [2, 2, 2]


array([-3, -3, -3])

In [44]:
print(a,b)
np.multiply(a, 2)  #Multiplying each element of the array by 2

[1, 2, 3] [2, 2, 2]


array([2, 4, 6])

In [45]:
print(a,b)
np.multiply(a,b) #Multiplying two arrays element-wise

[1, 2, 3] [2, 2, 2]


array([2, 4, 6])

In [46]:
print(a,b)
np.divide(a, b) #Dividing two arrays element-wise

[1, 2, 3] [2, 2, 2]


array([0.5, 1. , 1.5])

In [47]:
np.exp(a) #Calculating the exponential of each element in the array

array([ 2.71828183,  7.3890561 , 20.08553692])

In [48]:
np.sqrt(a) #Calculating the square root of each element in the array

array([1.        , 1.41421356, 1.73205081])

In [49]:
np.sqrt(36) #Calculating the square root of a single number

np.float64(6.0)

In [50]:
np.sin(a) #Calculating the sine of each element in the array

array([0.84147098, 0.90929743, 0.14112001])

In [51]:
np.sin(90) #Calculating the sine of 90 degrees

np.float64(0.8939966636005579)

In [52]:
np.cos(90)  #Calculating the cosine of 90 degrees

np.float64(-0.4480736161291701)

In [53]:
np.log(a) #Calculating the natural logarithm of each element in the array

array([0.        , 0.69314718, 1.09861229])

In [54]:
np.log(10) #Calculating the natural logarithm of a single number

np.float64(2.302585092994046)

# **Array Comparison**

In [55]:
print(a,b)
np.equal(a, b)  #Checking if two arrays are equal element-wise

[1, 2, 3] [2, 2, 2]


array([False,  True, False])

In [139]:
print(a,b)
np.array_equal(a, b)  #Checking if two arrays are equal element-wise

[1, 2, 3] [2, 2, 2]


False

# **Aggregate Functions**

# **BroadCasting**

# Rules OF BroadCasting
1.Both arrays have same dimensions
# OR
2.Any one array has a dimension 1

In [ ]:
a=np.array([[1, 2, 3, 4, 5],[6, 7, 8, 9, 10]])
b=np.array([6, 7, 8, 9, 10])    
a + b  #adding b to each row of a


array([[ 7,  9, 11, 13, 15],
       [12, 14, 16, 18, 20]])

In [86]:
a = np.array([1, 2, 3])
b = np.array([[1],[2],[3]])
a + b  # Broadcasting b to each row of a

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [ ]:
a=np.array([[1, 2, 3, 4, 5],[6, 7, 8, 9, 10]])
b=np.array([6, 7, 8, 9, 10])    
a - b  #Subtracting b from each row of a


array([[-5, -5, -5, -5, -5],
       [ 0,  0,  0,  0,  0]])

In [ ]:
a = np.array([1, 2, 3])
b = np.array([[1],[2],[3]])
a - b  

array([[ 0,  1,  2],
       [-1,  0,  1],
       [-2, -1,  0]])

In [88]:
a.ndim

1